---
# Configure all
- name: Configure all
  hosts: all
  become: true
  tasks:
  - name: Install the openvpn
    ansible.builtin.apt:
      name: openvpn
      update_cache: yes  
      
  - name: Install the iperf3
    ansible.builtin.apt:
      name: iperf3
      update_cache: yes    
